version: '3.8'

services:
  go-app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - go_db

  go_db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
