version: "3.8"

networks:
  my_network:
    driver: bridge

services:
  go-app:
    container_name: go-app
    image: lucassssmmmm1/atividade-devops-api-go:${DOCKER_IMAGE_TAG}
    build:
      context: .
      args:
        COMMIT_HASH: ${DOCKER_IMAGE_TAG}  # Passa o commit hash para o Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      go_db:
        condition: service_healthy  # Aguarda o banco estar pronto
    networks:
      - my_network
    
    env_file:
      - .env.prod

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - my_network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5

volumes:
  pgdata: {}
