name: CI/CD - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.generate_tag.outputs.sha }}

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Gerar Tag do Commit
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build da Imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/atividade-devops-api-go:${{ steps.generate_tag.outputs.sha }} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/atividade-devops-api-go:${{ steps.generate_tag.outputs.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/atividade-devops-api-go:latest

      - name: Push da Imagem para o Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/atividade-devops-api-go:${{ steps.generate_tag.outputs.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/atividade-devops-api-go:latest
