name: Go CI/CD

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env

      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
     

      - name: Build Docker Image
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "Commit Hash: $COMMIT_HASH"  # Debugging the commit hash
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/atividade-devops-api-go:${COMMIT_HASH} .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/atividade-devops-api-go:${COMMIT_HASH}
