name: Go CI/CD

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Commit Hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env

      - name: Install Dependencies
        run: go mod download

      - name: Build Go App
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Build Docker Image with Commit Hash
        run: |
          echo "Commit Hash: $COMMIT_HASH"
          docker build --build-arg COMMIT_HASH=$COMMIT_HASH -t go-api:$COMMIT_HASH .
        env:
          COMMIT_HASH: ${{ env.COMMIT_HASH }}

      - name: List Docker Images (Debug)
        run: docker images
